### ISSUE TITLE
"npm run e2e" fails

### ISSUE THREAD

**Issue by joh-klein** [mnemanja/weather-app#1]
```
1) Weather app should select new location.
  - Expected 'Leutewitzer Ring 62, 01169 Dresden, Deutschland edit_location' to equal 'Leutewitzer Ring 62, 01169 Dresden, Germany edit_location'.

2) Weather app should successfully change the location.
  - Failed: Wait timed out after 5053ms

Executed 12 of 12 specs (2 FAILED) in 10 secs.
```

**Comment by mnemanja** [comment]
Hello @joh-klein ,
Thanks for testing this app. It's much appreciated.

1) - Failed test due to the localization issue
2)  - I'll check to see what the problem with this one is

**Comment by mnemanja** [comment]
Both tests failed because of the same problem: **localization**, which has been fixed by making tests more flexible.
The fix will be in the next release which will occur soon.

Thank you for your patience and understanding.
