### ISSUE TITLE
Missing temp units weekly forcast

### ISSUE THREAD

**Issue by joh-klein** [mnemanja/weather-app#2]
It would be great, if the weekly forecast (great Idea btw) would not just display "27 / 13" but the correct units as well e.g. "27 °C/ 13 °C".

**Comment by mnemanja** [comment]
Hi @joh-klein ,
Thanks for the suggestion. I agree and I'll have it implemented asap.

Cheers,
Nemanja

**Comment by mnemanja** [comment]
Hi @joh-klein ,
I came to the decision to have the following temperature format, which is not exactly what you've suggested, but still more informative than it was previously: `27° / 13°`.
