### ISSUE TITLE
chart X-Axis for forecast days

### ISSUE THREAD

**Issue by joh-klein** [mnemanja/weather-app#4]
The X-Axis is from "9 PM" to "9 AM" which is not making too much sense. Maybe a timezone issue?

**Comment by mnemanja** [comment]
The X-Axis starts with the current time if viewing the current (today's) forecast. In any other case, it starts with the `12AM` mark.

For this app, I've used the https://darksky.net API and it is their current behavior.

If you haven't found this answer satisfactory, please re-open this issue.
